// Copyright (c) 2025-2026 f1ames0ff <f1am3sdev.github@protonmail.com>
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License along
// with this program; if not, write to the Free Software Foundation, Inc.,
// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
//

#version 460

#define DESC_SET_FRAMEBUFFERS 0
#define DESC_SET_GLOBAL_UNIFORM 1
#include "ShaderCommonGLSLFunc.h"

layout(local_size_x = COMPUTE_COMPOSE_GROUP_SIZE_X, local_size_y = COMPUTE_COMPOSE_GROUP_SIZE_Y, local_size_z = 1) in;

bool isLeftOutOfBounds(int checkerboardPix_X)
{
    return
        checkerboardPix_X == 0 ||
        checkerboardPix_X == getCheckerboardSeparatorX();
}

bool isRightOutOfBounds(int checkerboardPix_X)
{
    return
        checkerboardPix_X == getCheckerboardSeparatorX() ||
        checkerboardPix_X == int(globalUniform.renderWidth);
}

vec3 resolveCheckerboard( texture2D src, const ivec2 regularPix, const ivec2 checkerboardPix, const vec3 center )
{
    vec3 crossColor =
        0.25 * texelFetch( src, regularPix + ivec2( -1,  0 ), 0 ).rgb * float( !isLeftOutOfBounds( checkerboardPix.x ) ) +
        0.25 * texelFetch( src, regularPix + ivec2(  1,  0 ), 0 ).rgb * float( !isRightOutOfBounds( checkerboardPix.x ) ) +
        0.25 * texelFetch( src, regularPix + ivec2(  0,  1 ), 0 ).rgb +
        0.25 * texelFetch( src, regularPix + ivec2(  0, -1 ), 0 ).rgb;

    return mix( center, crossColor, 0.5 );
}

void main()
{
    const ivec2 pix             = ivec2( gl_GlobalInvocationID.x, gl_GlobalInvocationID.y );
    const ivec2 checkerboardPix = getCheckerboardPix( pix );

    if( pix.x >= uint( globalUniform.renderWidth ) || pix.y >= uint( globalUniform.renderHeight ) )
    {
        return;
    }

    vec3 hdr  = texelFetch( framebufPreFinal_Sampled, pix, 0 ).rgb;
    vec3 emis = texelFetch( framebufScreenEmisRT_Sampled, pix, 0 ).rgb;
    vec3 fog  = texelFetch( framebufAcidFogRT_Sampled, pix, 0 ).rgb;

    if( needResolveCheckerboard( checkerboardPix ) )
    {
        emis = resolveCheckerboard( framebufScreenEmisRT_Sampled, pix, checkerboardPix, emis );
        fog  = resolveCheckerboard( framebufAcidFogRT_Sampled, pix, checkerboardPix, fog );
    }

    imageStore( framebufFinal, pix, vec4( hdr, 0 ) );
    imageStore( framebufScreenEmission, pix, vec4( emis, 0 ) );
    imageStore( framebufAcidFog, pix, vec4( fog, 0 ) );
}
