// Copyright (c) 2026 QuakeRay contributors
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License along
// with this program; if not, write to the Free Software Foundation, Inc.,
// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
//

#version 460

#define DESC_SET_FRAMEBUFFERS 0
#define DESC_SET_GLOBAL_UNIFORM 1
#define DESC_SET_TONEMAPPING 2
#define TONEMAPPING_BUFFER_WRITEABLE
#include "ShaderCommonGLSLFunc.h"
#include "TonemappingUtils.glsl"

layout(local_size_x = COMPUTE_LUM_HISTOGRAM_GROUP_SIZE_X, local_size_y = COMPUTE_LUM_HISTOGRAM_GROUP_SIZE_Y, local_size_z = 1) in;


shared uint s_Histogram[HISTOGRAM_BINS];

void main()
{
    const ivec2 ipos = ivec2(gl_GlobalInvocationID);
    const ivec2 screenSize = ivec2(globalUniform.renderWidth, globalUniform.renderHeight);

    const bool validThread = !any(greaterThanEqual(ipos, screenSize));

    const vec3 input_color = validThread ? texelFetch(framebufPreFinal_Sampled, ipos, 0).rgb : vec3(0.0);

    const uint linear_idx = gl_LocalInvocationIndex;

    if (validThread && linear_idx < HISTOGRAM_BINS)
    {
        s_Histogram[linear_idx] = 0;
    }

    barrier();

    if (validThread && getLuminance(input_color) > 0.0)
    {
        const float lum = max(getLuminance(input_color), exp2(min_log_luminance));
        const float biased_log_luminance = log2(lum) * log_luminance_scale + log_luminance_bias;
        const float histogram_bin = clamp(biased_log_luminance * HISTOGRAM_BINS, 0.0, HISTOGRAM_BINS - 1.0);

        const uint left_bin = uint(histogram_bin);
        const uint right_bin = left_bin + 1;

        const float weight = clamp(1.0 - length(vec2(ipos) / vec2(screenSize) - vec2(0.5)) * 1.5, 0.01, 1.0);

        const float right_weight_F = fract(histogram_bin) * weight;
        const float left_weight_F = weight - right_weight_F;

        const uint right_weight_U = uint(right_weight_F * FIXED_POINT_FRAC_MULTIPLIER);
        const uint left_weight_U = uint(left_weight_F * FIXED_POINT_FRAC_MULTIPLIER);

        atomicAdd(s_Histogram[left_bin], left_weight_U);
        if (right_bin < HISTOGRAM_BINS)
        {
            atomicAdd(s_Histogram[right_bin], right_weight_U);
        }
    }

    barrier();

    if (validThread && linear_idx < HISTOGRAM_BINS)
    {
        const int localBinValue = int(s_Histogram[linear_idx]);
        if (localBinValue != 0)
        {
            atomicAdd(tonemapping.histogram[linear_idx], localBinValue);
        }
    }
}
