// Copyright (c) 2026 QuakeRay contributors
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License along
// with this program; if not, write to the Free Software Foundation, Inc.,
// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
//

#version 460

#include "EfSimple.inl"

vec3 hsv2rgb(vec3 c)
{
    vec4 K = vec4(1.0, 2.0 / 3.0, 1.0 / 3.0, 3.0);
    vec3 p = abs(fract(c.xxx + K.xyz) * 6.0 - K.www);
    return c.z * mix(K.xxx, clamp(p - K.xxx, 0.0, 1.0), c.y);
}

void main()
{
    const ivec2 pix = ivec2(gl_GlobalInvocationID.x, gl_GlobalInvocationID.y);

    if (!effect_isPixValid(pix))
    {
        return;
    }

    vec3 color = effect_loadFromSource(pix);

    const ivec2 rendPix = ivec2(effect_getFramebufUV(pix) * vec2(globalUniform.renderWidth, globalUniform.renderHeight));
    const vec3 albedo = texelFetch(framebufAlbedo_Sampled, rendPix, 0).rgb;


    float bw = getLuminance(color) + getLuminance(albedo) * 0.4;
    bw = clamp(bw * 1.5, 0, 1);

    const float h_scale = 0.7;
    const float h_offset = 0.65;
    float h = mod(h_offset + bw * h_scale, 1.0);

    vec3 dst = hsv2rgb(vec3(h, 1, clamp(sqrt(bw)+0.1, 0, 1)));

    effect_storeToTarget(mix(color, dst, getProgress()), pix);
}
