// Copyright (c) 2025-2026 f1ames0ff <f1am3sdev.github@protonmail.com>
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License along
// with this program; if not, write to the Free Software Foundation, Inc.,
// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
//

#version 460

#include "EfSimple.inl"

float getBW(vec3 color)
{
    return max(max(color.r, color.g), color.b);
}

void main()
{
    const ivec2 pix = ivec2(gl_GlobalInvocationID.x, gl_GlobalInvocationID.y);

    if (!effect_isPixValid(pix))
    {
        return;
    }

    vec3 color = effect_loadFromSource(pix);

    const ivec2 rendPix = ivec2(effect_getFramebufUV(pix) * vec2(globalUniform.renderWidth, globalUniform.renderHeight));
    const vec3 albedo = texelFetch(framebufAlbedo_Sampled, rendPix, 0).rgb;

    float bw = max(getBW(color), getBW(albedo));
    bw = sqrt(bw);

    const int L = 32;
    bw = clamp(int(bw * L), 0, L) / float(L);

    effect_storeToTarget(mix(color, vec3(1 - bw), getProgress()), pix);
}
