// Copyright (c) 2026 QuakeRay contributors
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License along
// with this program; if not, write to the Free Software Foundation, Inc.,
// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
//

#version 460

struct EffectWaves_PushConst
{
    float amplitude;
    float speed;
    float multX;
};

#define EFFECT_PUSH_CONST_T EffectWaves_PushConst
#include "EfSimple.inl"

float getMult(const ivec2 pix, float speed, float mult)
{
    return sin(
        globalUniform.time * mult * speed * 4  +
        pix.x / float(effect_getFramebufSize().x) * mult * 10);
}

void main()
{
    const ivec2 pix = ivec2(gl_GlobalInvocationID.x, gl_GlobalInvocationID.y);

    if (!effect_isPixValid(pix))
    {
        return;
    }

    float tx = getMult(pix, push.custom.speed, push.custom.multX);
    tx *= push.custom.amplitude * push.custom.multX * effect_getFramebufSize().x;

    float ty = getMult(pix, push.custom.speed, 1.0);
    ty *= push.custom.amplitude * effect_getFramebufSize().y;

    vec3 c = effect_loadFromSource(ivec2(pix.x + getProgress() * tx, pix.y + getProgress() * ty));
    effect_storeToTarget(c, pix);
}
