// Copyright (c) 2026 QuakeRay contributors
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License along
// with this program; if not, write to the Free Software Foundation, Inc.,
// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
//

#version 460
#extension GL_EXT_ray_tracing : require

#define MATERIAL_MAX_ALBEDO_LAYERS 0

#define DESC_SET_GLOBAL_UNIFORM 2
#define DESC_SET_VERTEX_DATA 3
#define DESC_SET_TEXTURES 4
#include "ShaderCommonGLSLFunc.h"

#include "TurbWarp.h"

hitAttributeEXT vec2 inBaryCoords;


#define ALPHA_THRESHOLD 0.5


void main()
{
	const ShTriangle tr = getTriangle(gl_InstanceID, gl_InstanceCustomIndexEXT, gl_GeometryIndexEXT, gl_PrimitiveID);

	const vec3 baryCoords = vec3(1.0f - inBaryCoords.x - inBaryCoords.y, inBaryCoords.x, inBaryCoords.y);
    const vec2 texCoord = getSurfaceTexCoord(tr.geometryInstanceFlags, tr.layerTexCoord[0] * baryCoords);

 	const vec4 color = getTextureSample(tr.materials[0][MATERIAL_ALBEDO_ALPHA_INDEX], texCoord) * tr.materialColors[0];

	if ((tr.geometryInstanceFlags & GEOM_INST_FLAG_ALPHA_TRANSMISSION) != 0)
	{
		uint h = uint(gl_InstanceID) * 73856093u ^ uint(gl_PrimitiveID) * 19349663u ^ globalUniform.frameId * 83492791u;
		h ^= h >> 13u;
		h *= 1274126177u;
		h ^= h >> 16u;

		if (float(h) * (1.0 / 4294967296.0) < 1.0 - color.a)
		{
			ignoreIntersectionEXT;
		}
	}
	else if ((color.r + color.g + color.b) / 3 * color.a + color.a < ALPHA_THRESHOLD)
	{
		ignoreIntersectionEXT;
	}

}
